multiple hwpe support in parallel
pulp-platform/hci pull request #45
Opened 2024-07-22 16:48 UTC by arpansur

I created and integrated an arbiter tree using the hci_arbiter to support multiple hwpes arbitration for wide port.

2024-07-22 20:11 UTC, FrancescoConti commented
I will give you a detailed review, but in the meantime one important question: are you sure that the multi-dimensional arrays of interfaces are synthesizable? I strongly suspect they are not.

2024-07-22 20:30 UTC, FrancescoConti requested changes
Mostly very minor comments. But the N-dimensional interface array are not convincing.

2024-07-22 20:30 UTC, FrancescoConti commented on rtl/common/hci_helpers.svh
> +`define HCI_INTF_2D_ARRAY(__name, __clk, __range2D, __range1D) `HCI_INTF_EXPLICIT_PARAM(__name[__range2D][__range1D], __clk, `HCI_SIZE_PARAM(__name))
See my comment on 2d, 3d interfaces: I am scared by these...

2024-07-22 20:30 UTC, FrancescoConti commented on rtl/core/hci_core_assign_expand.sv
> +    #(
same alignment as `module`

2024-07-22 20:30 UTC, FrancescoConti commented on rtl/core/hci_core_assign_expand.sv
> +  initial begin : width_checks
add `ifndef SYNTHESIS` clause

2024-07-22 20:30 UTC, FrancescoConti commented on rtl/core/hci_core_r_id_filter.sv
> +parameter int unsigned N_OUTSTANDING = 2,
fix alignment on these lines, remove all tabs

2024-07-22 20:30 UTC, FrancescoConti commented on rtl/core/hci_core_r_id_filter.sv
> +assign tcdm_target.gnt        = tcdm_initiator.gnt;
fix alignment

2024-07-22 20:30 UTC, FrancescoConti commented on rtl/core/hci_core_r_id_filter.sv
> +      .flush_i(clear_i),
fix alignments

2024-07-22 20:30 UTC, FrancescoConti commented on rtl/core/hci_core_source.sv
> +          stream_data_aligned[DATA_WIDTH-1:0] = stream_data_misaligned[DATA_WIDTH-1:0];
this is unrelated to the PR... isn't it already in another PR?

2024-07-22 20:30 UTC, FrancescoConti commented on rtl/hci_interconnect.sv
> +  `HCI_INTF_2D_ARRAY(hwpe_mem, clk_i, 0:N_HWPE-1, 0:N_MEM-1);
see comment on multi-dimensional arrays.

2024-07-22 20:30 UTC, FrancescoConti commented on rtl/hci_interconnect.sv
> +          hci_router #(
fix all alignments in this block

2024-07-22 20:30 UTC, FrancescoConti commented on rtl/interco/hci_arbiter_tree.sv
> +  hci_core_intf.target    in    			   [0:NB_REQUESTS-1][0:NB_CHAN-1],
same as above. one possible alternative is a single `[0:NB_REQUESTS*NB_CHAN-1]` array... requires a bit more boilerplate though.

2024-07-22 20:30 UTC, FrancescoConti commented on rtl/interco/hci_arbiter_tree.sv
> +							.in_high ( in[ii] 			   ),
fix alignments

2024-07-22 20:30 UTC, FrancescoConti commented on rtl/interco/hci_router.sv
> +    .FILTER_WRITE_R_VALID(FILTER_WRITE_R_VALID)
alignments

2024-07-22 20:30 UTC, FrancescoConti commented on rtl/core/hci_core_r_id_filter.sv
> +   fifo_v3 #(
i am not a huge fan of depending on `common_cells`... but ok.

2024-07-23 19:09 UTC, arpansur commented
> I will give you a detailed review, but in the meantime one important question: are you sure that the multi-dimensional arrays of interfaces are synthesizable? I strongly suspect they are not.

Yes, you are right! I removed the reliance on the 2D interfaces

2024-07-23 19:11 UTC, arpansur commented on rtl/core/hci_core_assign_expand.sv
> +    #(
It seems like github aligns TAB differently. I aligned them too!

2025-02-27 10:25 UTC, sermazz requested changes
I rebased this branch on top of the latest modifications to the HCI done for Astral (https://github.com/pulp-platform/hci/tree/astral-v1.0), so that I could use it in our Cluster pv2.
Please chek: https://github.com/pulp-platform/hci/tree/smazzola/chimera
Can we change the origin branch of this PR to smazzola/chimera? Or I open another PR and we close this? @FrancescoConti @arpansur

2025-02-27 11:20 UTC, FrancescoConti commented
I am not sure we can change the origin (we can change the base from the PR interface), so I'd say let's open a new PR and then we close this one mentioning the new PR.

2025-02-27 13:28 UTC, FrancescoConti commented
I am not sure we can change the origin (we can change the base from the PR interface), so I'd say let's open a new PR and then we close this one mentioning the new PR.

2025-03-07 21:44 UTC, closed without merging

2025-03-07 21:44 UTC, FrancescoConti commented
As discussed I opened #53, which supersedes this PR