Add User Signals
pulp-platform/hci pull request #6
Opened 2021-01-26 17:24 UTC by micprog

This PR add optional `user` and `r_user` signals parallel to `data` and `r_data`, respectively. Width of the user signals can be set using `UW`, default is 0. Most modules are updated to support the user signals, except the following modules which ignore user inputs and set user outputs to `'0`:
- `hci_core_sink`
- `hci_core_source`
- `hci_core_split`
- `hci_hwpe_interconnect` (please note that this may adversely affect `hci_interconnect`)

There are some further modification regarding consistent addressing in the interconnects, as well as modification to default values for more consistency.

2021-01-27 12:09 UTC, FrancescoConti requested changes
In general, all good. Two important points:
- split changes related to `ADDR_MEM_WIDTH` to a different PR -- these are pretty critical and could cause subtle bugs.
- please revert style changes, or split them out to a different PR. Here there is a complicated trade-off: on the one hand there are the "established style rules". On the other hand, there is the fact that HWPE-related repos have followed the current K&R style since before we even started discussing style changes, and we tried to be consistent there. To me it should be an all-or-nothing choice, on which I am very opinionanted, and which anyways deserves its own PR.

2021-01-27 12:09 UTC, FrancescoConti commented on rtl/interco/hci_new_log_interconnect.sv
> +  logic [N_MEM-1:0] [AWM-3:0]   mems_add;
Same as before, split in another PR

2021-01-27 12:09 UTC, FrancescoConti commented on rtl/interco/hci_new_log_interconnect.sv
> +      assign mems[i].add [AWM-1:2]          = mems_add   [i];
Split

2021-01-27 12:09 UTC, FrancescoConti commented on rtl/interco/hci_new_log_interconnect.sv
> +    .ADDR_MEM_WIDTH ( AWM-2  ),
Split

2021-01-27 14:10 UTC, micprog commented
Thank you for your feedback! I will split up the pull requests to one regarding memory, and one regarding user signals. Sorry about the formatting changes, I was referring to [lowRISC's style guide](https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md), but will revert the changes to styling, I was not aware of the different standard used.

2021-01-27 14:26 UTC, micprog commented on rtl/core/hci_core_split.sv
> +  // User bits not implemented in split
There are two options here, and while only one seems initially feasible to me, I don't know how much sense it makes.
1. Split user bits, similar to how data bits are split (`in_UW = N* out_UW`)
2. Assign all user bits without splitting (`in_UW == out_UW`). This causes an issue with the return channel, as to assign back in the return channel either all user values would need to be the same, one would need to be selected, or another logic operation performed. While this seems complicated, such behavior could make sense in case user bits are used for individual signalization (e.g. to indicate a special operations such as atomics).

For what I intend to use the user bits, a custom module would need to be implemented for split regardless (recalculation of ECC bits), so I decided to leave this unimplemented for now. Let me know if you would prefer one of the behaviors, I can implement it.

2021-01-29 10:19 UTC, FrancescoConti commented on rtl/core/hci_core_split.sv
> +  // User bits not implemented in split
Yes, in fact 2 is what I had in mind. Let's keep the comment, I think that's ok.

2021-01-29 10:24 UTC, FrancescoConti requested changes
I saw the improvements! I don't know if it was a work-in-progress though, you should still split out all changes related to `AWC` and `AWM` parameters when instantiating LICs.

2021-01-29 10:24 UTC, FrancescoConti commented on rtl/hci_interconnect.sv
> -        .AWM    ( AWM-2               ),
I think this one slipped :)

2021-01-29 10:24 UTC, FrancescoConti commented on rtl/hci_interconnect.sv
> -        .AWM    ( AWM-2               ),
Same here?

2021-01-29 10:24 UTC, FrancescoConti commented on rtl/interco/hci_log_interconnect.sv
> +  logic [N_MEM-1:0] [AWM-3:0]   mems_add;
same here

2021-01-29 10:24 UTC, FrancescoConti commented on rtl/interco/hci_log_interconnect.sv
> +      assign mems[i].add [AWM-1:2]          = mems_add   [i];
same here

2021-01-29 10:57 UTC, micprog commented on rtl/hci_interconnect.sv
> -        .AWM    ( AWM-2               ),
I split out the `AWM/AWC` changes to a different PR (#7), but left the changes here as well to properly instantiate parameters for the memory interface:
https://github.com/micprog/hci/blob/496e277cf4270e61e99530f9f8e06f3658c72248/rtl/hci_interconnect.sv#L62-L66
Defining the proper `AWM` for this interface, without the `AWM` changes, results in warnings regarding signal width mismatch as the default is wider than the bits used. My thought process was to merge the other PR first and avoid conflicts in the future, with commit 94274b6 updating defaults, and commit 4c74afc changing the `AWM` things, both part of #7, but also this PR as I did my developments with all updates (commit 194b969 adds the user signals, on top of the two other commits). If you prefer, I can change this PR to not include the `AWM` updates, however this will likely lead to conflicts when merging either PR.

2021-01-29 11:31 UTC, FrancescoConti commented on rtl/hci_interconnect.sv
> -        .AWM    ( AWM-2               ),
Ok, the procedure you suggest is fine. I thought of doing the opposite simply because the addition of the user signals is an easy change (fundamentally non-breaking) which I can merge rapidly, but changing the address bits is touching a viper's nest (because what I mean and document as `AW` address width is different from what is meant on the LIC side). To be very honest, risking a subtle bug where half the cluster's L1 is not accessible because we want to hide a warning is not worth it -- better to do things properly 😄 

See the #7 for details.

2021-01-29 16:22 UTC, micprog commented on rtl/hci_interconnect.sv
> -        .AWM    ( AWM-2               ),
Ok, I separated the commit regarding `AWM` updates from this PR, will work on properly testing that change in #7. This should now only include updates on defaults, and addition of user signals.

2021-02-08 14:13 UTC, FrancescoConti approved these changes
LGTM. Let me know if you want to check & merge #7 first, otw I'll proceed with this.

2021-02-08 14:18 UTC, micprog commented
> LGTM. Let me know if you want to check & merge #7 first, otw I'll proceed with this.

I haven't properly checked #7 yet, but this is now separated so it can be merged first.

2021-02-08 14:19 UTC, merged