substituted XBAR_TCDM with tcdm_interconnect
pulp-platform/hci pull request #9
Opened 2021-04-12 17:19 UTC by luca-valente

2021-04-13 08:28 UTC, luca-valente commented
I validated the changes against this test https://github.com/pulp-platform/regression_tests/tree/master/tcdm_tests/L1_control_check   that writes and reads the whole L1 from the SoC.

Would you like me to add also your multi-core test to the regressions?

2021-04-13 08:43 UTC, FrancescoConti commented on rtl/interco/hci_log_interconnect.sv
> +      assign mems[i].id                = '0;
maybe just add a comment `// not used inside tcdm_interconnect`

2021-04-13 08:45 UTC, FrancescoConti requested changes
Perfect, but should there be changes in Bender.yml as well? I don't have a working setup to test those, but better to double check.

2021-04-13 13:59 UTC, luca-valente commented on rtl/interco/hci_log_interconnect.sv
> +      assign mems[i].id                = '0;
done!

2021-04-13 14:02 UTC, luca-valente commented
I changed the `Bender.yml` accordingly, to add the `tcdm_interconnect` dependencies. Also, I tested the changes against this test https://github.com/FrancescoConti/lfsr32CheckL1 with `#define ADDR_LAST  0x10010000` and it works properly also with it.

2021-04-13 19:57 UTC, FrancescoConti commented
@micprog can you please review if my merge of `UW` user width is suitable for you?

2021-04-14 12:58 UTC, micprog requested changes
Other than the two changes I noted, everything looks good to me. I ran a quick test with added UW bits and bender, which worked for me after the minor changes.

2021-04-14 12:58 UTC, micprog commented on rtl/interco/hci_log_interconnect.sv
> +    .ByteOffWidth ( $clog2(DW-1)-3              ), // determine byte offset from real data width
I believe the following line is also needed for proper `UW` compatibility:
`.BeWidth ( DW/BW ),`

2021-04-14 12:58 UTC, micprog commented on rtl/interco/hci_log_interconnect.sv
>        assign mems[i].id                = mems_ID    [i];
I think this line was re-added with the merge from master, you may want to remove this.

2021-04-14 13:18 UTC, luca-valente commented on rtl/interco/hci_log_interconnect.sv
> +    .ByteOffWidth ( $clog2(DW-1)-3              ), // determine byte offset from real data width
Hi @micprog  ! Peraphs we should also chance `.ByteOffWidth ( $clog2(DW-1)-3              )` to `ByteOffWidth ( $clog2(DW+UW-1)-3              )`. What do you think?

2021-04-14 13:23 UTC, luca-valente commented on rtl/interco/hci_log_interconnect.sv
> +    .ByteOffWidth ( $clog2(DW-1)-3              ), // determine byte offset from real data width
Actually, it looks good already fine like this, let me know if I am wrong. While the `.BeWidth ( DW/BW )` should be done! Thanks :)

2021-04-14 13:32 UTC, micprog commented on rtl/interco/hci_log_interconnect.sv
> +    .ByteOffWidth ( $clog2(DW-1)-3              ), // determine byte offset from real data width
No, as the user bits are not intended to contain data, but metadata. To the specific use-case I added it for, I added ECC protection to the data, meaning the stored data and addressing remains the same, with additional bits only for error correction, not impacting the rest of the system. If I'm not mistaken, the `ByteOffWidth` is used for proper bank selection and thus should depend only on data, not metadata (see https://github.com/pulp-platform/cluster_interconnect/blob/2dc55ed7f6dc03c405c256dd9107ae0159328708/rtl/tcdm_interconnect/tcdm_interconnect.sv#L29-L31).

2021-04-14 13:34 UTC, micprog approved these changes
LGTM

2021-04-14 13:37 UTC, luca-valente commented
Just tested again the L1 tests, both passed. https://github.com/pulp-platform/regression_tests/tree/master/tcdm_tests

2021-04-14 13:44 UTC, FrancescoConti approved these changes

2021-04-14 13:44 UTC, FrancescoConti commented
LGTM, I'll merge

2021-04-14 13:45 UTC, merged